services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=igestant
      - MYSQL_ROOT_PASSWORD=02122001Luan
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data: