type Card {
  id: String
  question: String
  shortAnswer: String
  longAnswer: String
  reference: String
}

input CreateCardInput {
  question: String!
  shortAnswer: String!
  longAnswer: String!
  reference: String!
}

input UpdateCardInput {
  id: String!
  question: String
  shortAnswer: String
  longAnswer: String
  reference: String
}

input DeleteCardInput {
  id: String!
}

input loginInput {
  email: string
  password: string
}

type Query {
  readCard: [Card]!
}

type Mutation {
  createCard(input: CreateCardInput!): Card!
  updateCard(input: UpdateCardInput): Card
  deleteCard(input: DeleteCardInput): Card
  loginUser(input: loginInput): String
}